Update Zeebe to 8.2.0-rc1
camunda-community-hub/eze pull request #275
Opened 2023-03-28 14:34 UTC by skayliu

## Description

- Update Zeebe from `8.2.0-alpha5` to `8.2.0-rc1`
- Add EngineConfiguration ([[Enable message time-to-live checker configuration]#11956](https://github.com/camunda/zeebe/pull/11956)) and JobStreamer parameters
- Support new signal broadcast API
- Implement new signal broadcast API
- Add filter option for Signal and Signal Subscription Record Streams
- [Disable delete resource test #12111](https://github.com/camunda/zeebe/pull/12111)

2023-03-28 14:51 UTC, skayliu commented
Hey, @saig0 @Zelldon, The `should broadcast signal` test case works well on my pc, could you check it? Thank you.

2023-03-28 15:16 UTC, skayliu commented
And `should increase the time` test may fail, the related Zeebe PR [Message TTL Checker goes idle when needed](https://github.com/camunda/zeebe/pull/11959)

2023-03-29 11:12 UTC, saig0 commented
@skayliu thank you for your contribution. :tada: 

I will have a look at your changes soon. :eyes:

2023-03-29 12:10 UTC, saig0 requested changes
@skayliu nice job. :tada: The changes look good. :rock: 

I had a look at the failing test cases and found a solution. Please check my comments. :cookie:

2023-03-29 12:10 UTC, saig0 commented on eze/src/test/kotlin/org/camunda/community/eze/EngineClientTest.kt
Locally, the test case `should increase the time` fails for me.

```
java.lang.NullPointerException: Parameter specified as non-null is null: method org.camunda.community.eze.db.EzeDbColumnFamily.whileTrue, parameter startAtKey
	at org.camunda.community.eze.db.EzeDbColumnFamily.whileTrue(EzeDbColumnFamily.kt) ~[classes/:?]
	at io.camunda.zeebe.engine.state.message.DbMessageState.visitMessagesWithDeadlineBeforeTimestamp(DbMessageState.java:351) ~[zeebe-workflow-engine-8.2.0-rc1.jar:8.2.0-rc1]
	at io.camunda.zeebe.engine.processing.message.MessageTimeToLiveChecker.execute(MessageTimeToLiveChecker.java:76) ~[zeebe-workflow-engine-8.2.0-rc1.jar:8.2.0-rc1]
	at io.camunda.zeebe.stream.impl.ProcessingScheduleServiceImpl.lambda$toRunnable$5(ProcessingScheduleServiceImpl.java:135) ~[zeebe-stream-platform-8.2.0-rc1.jar:8.2.0-rc1]
```

I was able to fix the issue by adjusting [EzeDbColumnFamily.kt#whileTrue()](https://github.com/camunda-community-hub/eze/blob/main/eze/src/main/kotlin/org/camunda/community/eze/db/EzeDbColumnFamily.kt#L354C18-L361).

With the latest Zeebe version, the `startAtKey` parameter is invoked with `null`. So, the method should be able to handle `null`. 

For example by changing the method to:

```kotlin
    override fun whileTrue(startAtKey: KeyType?, visitor: KeyValuePairVisitor<KeyType, ValueType>) {
        startAtKey?.let {
            whileWithPrefix(
                context = context,
                prefix = it,
                keyInstance = keyInstance,
                valueInstance = valueInstance,
                visitor = visitor
            )
        } ?: whileTrue(visitor)
    }
```

2023-03-29 13:13 UTC, skayliu commented
@saig0, It's all done, please review again, thank you.

2023-03-29 13:23 UTC, saig0 approved these changes
@skayliu lightning fast. :zap: Thank you for your fast reaction. :cake: 

The PR is ready to merge. :rocket:

2023-03-29 13:24 UTC, merged